version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8081:8080"   # Jenkins web UI
      - "50000:50000" # Jenkins agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Give Jenkins access to Docker

volumes:
  jenkins_home:
